16-comments-list-api
W-Shih/django-twitter pull request #24
Opened 2021-11-25 23:02 UTC by W-Shih

- feature: add comments-list-api
- test: add tests for comments-list-api
- lint: Enable wrong-import-order

2021-11-25 23:06 UTC, wen-wayne-shih commented on comments/api/tests.py
> +        self.assertEqual(response.status_code, status.HTTP_405_METHOD_NOT_ALLOWED)
Remove TODO

2021-11-25 23:08 UTC, wen-wayne-shih requested changes
address before merging

2021-11-25 23:08 UTC, wen-wayne-shih commented on comments/api/tests.py
> +        self.assertEqual(response.status_code, status.HTTP_405_METHOD_NOT_ALLOWED)
Remove TODO

2021-11-25 23:08 UTC, wen-wayne-shih commented on comments/api/views.py
> +    # permission_classes = [IsAuthenticated, IsObjectOwner]
Remove TODO

2021-11-26 00:17 UTC, W-Shih commented on comments/api/views.py
> +    # permission_classes = [IsAuthenticated, IsObjectOwner]
Resolved as per suggestion

2021-11-26 00:17 UTC, W-Shih commented on comments/api/tests.py
> +        self.assertEqual(response.status_code, status.HTTP_405_METHOD_NOT_ALLOWED)
Resolved as per suggestion

2021-11-26 00:17 UTC, W-Shih commented on comments/api/tests.py
> +        self.assertEqual(response.status_code, status.HTTP_405_METHOD_NOT_ALLOWED)
Resolved as per suggestion

2021-11-26 00:19 UTC, wen-wayne-shih requested changes
Squash commits before merging

2021-11-26 00:20 UTC, wen-wayne-shih approved these changes

2021-11-26 00:23 UTC, merged