22 likes model and admin
W-Shih/django-twitter pull request #30
Opened 2022-02-24 10:51 UTC by W-Shih

- feature: add likes model and admin
- test: add tests for likes model
- misc: update lint and migration

2022-02-24 19:45 UTC, wen-wayne-shih requested changes

2022-02-24 19:45 UTC, wen-wayne-shih commented on likes/models.py
> +from django.db import models
- update the import order

2022-02-25 08:19 UTC, W-Shih commented on likes/models.py
> +from django.db import models
Resolved as suggestion

2022-02-25 08:20 UTC, wen-wayne-shih approved these changes

2022-02-25 08:21 UTC, merged